### ISSUE TITLE
Nebulex `v3.0.0-rc.1` roadmap

### ISSUE THREAD

**Issue by cabol** [elixir-nebulex/nebulex#189]
# Nebulex v3.0.0-rc.1

- [x] Ok/Error tuple Cache API.
- [x] Remove adapter implementations from Nebulex since they will be moved to separate repositories. Nebulex repo will only keep the generics, like the APIs, annotations, overall utilities, etc.
- [x] All cache commands optionally support passing the wanted dynamic cache (name or PID) as the first argument to directly interact with a cache instance (additional to `c:get_dynamic_cache/0` `c:put_dynamic_cache/1`, `c:with_dynamic_cache/2`).
- [x] Deprecate `Nebulex.Adapter.Stats` behaviour in favor of `Nebulex.Adapter.Info`. Instead of having a behaviour that only returns cache stats, the idea is to have a more generic or broader behaviour `Nebulex.Adapter.Info` to return stats and more information about the cache, such as consumed memory, etc.
- [x] Deprecate `Nebulex.Adapter.Persistence` behaviour. The current implementation only supports dumping the cache entries into a local file. It is quite a limited approach. Persistence can be implemented in many different ways depending on the use case. A persistence API with a specific implementation may not be very useful because it won't cover all possible use cases. For example, if your application is on AWS, perhaps it makes more sense to use S3 as persistent storage, not the local file system. Since Nebulex v3, persistence is an add-on that should be provided by the backend (e.g., Redis), another library, or the application itself. And it should be configured via the adapter's configuration (or maybe directly with the backend).
- [x] Support dynamic cache in decorators.
- [x] Evaluate the `:cache` option for decorated functions in runtime.
- [x] Telemetry events for cache commands out-of-box.
- [x] Unify `all` and `get_all` into one single callback `get_all`. The callback `get_all` will belong to the Query API and will support the predefined query `{:in, keys}` for getting multiple keys simultaneously.
- [x] New option/flag `:bypass_mode` to bypass the cache while running tests.
- [x] Fix possible inconsistencies on caching decorators when using references (reported in #215).
- [x] Review and fix the guides to ensure they are consistent with the v3 changes.
- [x] Review and fix the docs, ensuring proper grammar, no typos, mistakes, inconsistencies, etc.

## New APIs

- [x] `Nebulex.Adapter.Info` – An interface to return cache information like stats, memory, etc.
- [x] `Nebulex.Adapter.Observable` – A tagging interface for cache entry event handlers. Maintains a registry of handlers and invokes them to handle cache entry events.
- [x] Add docs and examples of `Nebulex.Adapter.Info` to the "Getting Started" guide.

### Adapters

- [x] Move the `Nebulex.Adapters.Local` adapter to a separate [repository](https://github.com/nebulex-project/nebulex_local) supporting the API v3.
- [x] Move the `Nebulex.Adapters.Partitioned` adapter to a separate [repository](https://github.com/nebulex-project/nebulex_distributed) supporting the API v3.
- [x] Move the `Nebulex.Adapters.Multilevel` adapter to a separate [repository](https://github.com/nebulex-project/nebulex_distributed) supporting the API v3.
- [x] Migrate [nebulex_redis_adapter](https://github.com/elixir-nebulex/nebulex_redis_adapter) to v3.
- [x] Migrate [nebulex_adapters_cachex](https://github.com/elixir-nebulex/nebulex_adapters_cachex) to v3.
